name: auth_dart
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_cors_headers: ^0.1.5
  jwt_decoder: ^2.0.1
  crypto: ^3.0.3
  sqlite3: ^2.4.0
  bcrypt: ^1.1.3

dev_dependencies:
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
