name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.0'
    
    - name: Install dependencies
      run: dart pub get
      
    - name: Analyze project source
      run: dart analyze
      
    - name: Run tests
      run: dart test
      
    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed . 